# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'placepic' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod "TLPhotoPicker"
  pod 'Alamofire', '~> 4.8.2'
  pod 'Kingfisher', '~> 5.0'
  pod 'lottie-ios'
  pod 'Firebase/Analytics'
  pod 'Firebase/Core'
  pod 'NMapsMap'

  # Pods for placepic

end
